#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "twikoo"
database_id = "31c9f521-21d0-4f11-ab9a-0537d3d02468"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "twikoo.r2.hongchenduzhe.qzz.io"

[dev]
port = 5000
